version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
      - test


jobs:
  test:
    resource_class: large
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Install visualization dependencies
          command: |
            viz/scripts/install-dependencies.sh
      - run:
          name: Load Umbra Docker image
          command: |
            . umbra/scripts/vars.sh
            # ${UMBRA_URL_PREFIX} should be set as a sercet variable
            curl -s ${UMBRA_URL_PREFIX}${UMBRA_VERSION}.tar.gz | docker load
      - run:
          name: Setup
          command: |
            export DEBIAN_FRONTEND=noninteractive
            sudo apt update
            # install dependencies
            sudo apt install -y wget unzip
            scripts/install-dependencies.sh
      - run:
          name: Download data sets
          command: |
            # Cypher
            cd cypher
            ## compressed CSVs for Cypher
            scripts/get-sample-data-set.sh
            ## uncompressed CSVs for Cypher
            wget -q https://ldbcouncil.org/ldbc_snb_datagen_spark/social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            unzip -q social-network-sf0.003-bi-composite-projected-fk-neo4j.zip
            cd ..
            # Umbra
            cd umbra
            ## CSVs for Umbra
            scripts/get-sample-data-set.sh
            cd ..
            # TigerGraph
            cd tigergraph
            scripts/get-sample-data-set.sh
            cd ..
      - run:
          name: Download factors
          command: |
            cd paramgen
            scripts/get-sample-factors.sh
            cd ..
      - run:
          name: Generate parameters
          command: |
            cd paramgen
            scripts/paramgen.sh
            cd ..
            head -n 5 parameters/*.csv
      - run:
          name: Test Umbra toolchain
          command: |
            cd umbra
            . scripts/use-sample-data-set.sh
            scripts/load-in-one-step.sh
            scripts/backup-database.sh
            scripts/restore-database.sh
            scripts/benchmark.sh --test
            scripts/stop.sh
            cd ..
            scripts/scoring.sh umbra
      - run:
          name: Test Cypher toolchain with uncompressed CSVs
          command: |
            cd cypher
            export SF=0.003
            export NEO4J_CSV_DIR=`pwd`/social-network-sf${SF}-bi-composite-projected-fk-neo4j/graphs/csv/bi/composite-projected-fk/
            scripts/load-in-one-step.sh
            scripts/benchmark.sh --test
            scripts/stop.sh
            cd ..
            scripts/cross-validate.sh cypher umbra
            scripts/scoring.sh cypher
      - run:
          name: Test Cypher toolchain with compressed CSVs
          command: |
            # the sample data set contains compressed CSVs
            cd cypher
            . scripts/use-sample-data-set.sh
            scripts/load-in-one-step.sh
            scripts/backup-database.sh
            scripts/restore-database.sh
            scripts/benchmark.sh --test
            scripts/stop.sh
            cd ..
            scripts/cross-validate.sh cypher umbra
            scripts/scoring.sh cypher
      - run:
          name: Test TigerGraph toolchain with compressed CSVs
          command: |
            # the sample data set contains compressed CSVs
            cd tigergraph
            . scripts/configure-data-set.sh
            scripts/load-in-one-step.sh
            scripts/benchmark.sh --test
            scripts/stop.sh
            cd ..
            scripts/cross-validate.sh tigergraph umbra
            scripts/scoring.sh tigergraph
      - slack/status
